/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    BirthdayList: typeof import('./src/components/BirthdayList.vue')['default']
    BirthdaySkeleton: typeof import('./src/components/skeleton/BirthdaySkeleton.vue')['default']
    Button: typeof import('primevue/button')['default']
    ButtonShare: typeof import('./src/components/ButtonShare.vue')['default']
    Card: typeof import('primevue/card')['default']
    Carousel: typeof import('primevue/carousel')['default']
    Chips: typeof import('primevue/chips')['default']
    ColorPicker: typeof import('primevue/colorpicker')['default']
    ColumnContent: typeof import('./src/components/ColumnContent.vue')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    Drawer: typeof import('primevue/drawer')['default']
    Empty: typeof import('./src/components/Empty.vue')['default']
    EventList: typeof import('./src/components/EventList.vue')['default']
    EventSkeleton: typeof import('./src/components/skeleton/EventSkeleton.vue')['default']
    Form: typeof import('@primevue/forms/form')['default']
    FormField: typeof import('@primevue/forms/formfield')['default']
    IconField: typeof import('primevue/iconfield')['default']
    Image: typeof import('primevue/image')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    InstallPrompt: typeof import('./src/components/InstallPrompt.vue')['default']
    Knob: typeof import('primevue/knob')['default']
    Menu: typeof import('primevue/menu')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Message: typeof import('primevue/message')['default']
    OperatorArsenal: typeof import('./src/components/operators/OperatorArsenal.vue')['default']
    OperatorDetails: typeof import('./src/components/operators/OperatorDetails.vue')['default']
    OperatorLoadout: typeof import('./src/components/operators/OperatorLoadout.vue')['default']
    OperatorRankCard: typeof import('./src/components/operators/OperatorRankCard.vue')['default']
    Private: typeof import('./src/components/header/Private.vue')['default']
    Public: typeof import('./src/components/header/Public.vue')['default']
    Qrcode: typeof import('./src/components/operators/Qrcode.vue')['default']
    RadarStats: typeof import('./src/components/gamification/RadarStats.vue')['default']
    ReloadPrompt: typeof import('./src/components/ReloadPrompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('primevue/skeleton')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
  }
  export interface GlobalDirectives {
    Ripple: typeof import('primevue/ripple')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
