import type { ChartOptions, ChartData, TooltipItem } from "chart.js";

export const TEAM_NAME = import.meta.env.VITE_TEAM_NAME;
export const TEAM_TAG = import.meta.env.VITE_TEAM_TAG;
export const TEAM_MOTTO = import.meta.env.VITE_TEAM_MOTTO;
export const MONTHLY_FEE = Number.parseFloat(import.meta.env.VITE_MONTHLY_FEE);
export const DUE_DATE = Number.parseInt(import.meta.env.VITE_DUE_DATE, 10);

export const MIN_COMPLETE_UNIFORMS = 3;
export const EXPERIENCE_PER_LEVEL = 200;
export const MIN_VOTES_REQUIRED = 6;
export const DEADLINE_HOUR = 22;
export const MAX_FILE_SIZE = 5 * 1024 * 1024;

export const EVENT_TYPES = {
  1: "Jogo",
  2: "Evento",
  3: "Manutenção",
  4: "Curso",
  5: "Reunião",
  6: "Outros",
};

export const XP_VALUES = {
  GAME: 100, // Jogo normal
  MAINTENANCE: 200, // Manutenção de campo/equipamento
  PRESENCE: 25, // Reunião ou presença rápida
  COURSE: 400, // Cursos e treinamentos oficiais
};

export const LEVELS = [
  {
    min: 1,
    max: 5,
    label: "Iniciado em Campo",
    description: "Aprendendo os fundamentos da operação.",
  },
  {
    min: 6,
    max: 10,
    label: "Operador de Linha",
    description: "Já conhece o terreno e executa ordens com precisão.",
  },
  {
    min: 11,
    max: 15,
    label: "Especialista Urbano",
    description: "Domina táticas de CQB e progressão em grupo.",
  },
  {
    min: 16,
    max: 20,
    label: "Batedor de Vanguarda",
    description: "O primeiro a entrar, o último a sair.",
  },
  {
    min: 21,
    max: 25,
    label: "Atirador Designado",
    description: "Precisão absoluta em distâncias críticas.",
  },
  {
    min: 26,
    max: 30,
    label: "Estrategista de Setor",
    description: "Capaz de coordenar pequenas esquadras em combate.",
  },
  {
    min: 31,
    max: 35,
    label: "Lobo da Floresta",
    description: "Especialista em camuflagem e operações de longa duração.",
  },
  {
    min: 36,
    max: 40,
    label: "Mestre de Armas",
    description: "Conhecimento total de mecânica e balística.",
  },
  {
    min: 41,
    max: 45,
    label: "Veterano de Elite",
    description: "Resiliência testada em inúmeras missões.",
  },
  {
    min: 46,
    max: 49,
    label: "Sombra da Unidade",
    description: "Invisível para o inimigo, letal para o objetivo.",
  },
  {
    min: 50,
    max: 50,
    label: "O Fantasma",
    description: "A lenda viva do time. Sua presença altera o rumo da missão.",
  },
  {
    min: 51,
    max: 55,
    label: "Comandante de Campo",
    description: "Visão tática privilegiada. Líder nato sob fogo cruzado.",
  },
  {
    min: 56,
    max: 60,
    label: "Operador Black Ops",
    description:
      "Especialista em missões de alto risco onde falhar não é opção.",
  },
  {
    min: 61,
    max: 65,
    label: "Sentinela de Ferro",
    description:
      "Uma barreira inquebrável. Defende o objetivo com maestria absoluta.",
  },
  {
    min: 66,
    max: 70,
    label: "Infiltrador Mestre",
    description: "Capaz de desmantelar qualquer defesa inimiga por dentro.",
  },
  {
    min: 71,
    max: 75,
    label: "Lenda do Asfalto",
    description: "Experiência forjada em anos de CQB intenso e urbano.",
  },
  {
    min: 76,
    max: 80,
    label: "General de Divisão",
    description:
      "Sua autoridade e conhecimento são respeitados por todo o comando.",
  },
  {
    min: 81,
    max: 85,
    label: "Águia de Rapina",
    description:
      "Sempre um passo à frente. Antecipa o inimigo antes do contato.",
  },
  {
    min: 86,
    max: 90,
    label: "Titã da Unidade",
    description:
      "Uma força da natureza em campo. Temido por qualquer adversário.",
  },
  {
    min: 91,
    max: 95,
    label: "Oráculo de Guerra",
    description:
      "Mestre em inteligência. Cada tiro é um passo para a vitória certa.",
  },
  {
    min: 96,
    max: 99,
    label: "Guardião do Êxodo",
    description: "O protetor máximo da honra e dos valores do time.",
  },
  {
    min: 100,
    max: 100,
    label: "O Mito de Platina",
    description:
      "O topo absoluto. Ninguém superou seus feitos. Uma inspiração para todos.",
  },
];

export const calculateLevel = (xp: number) => {
  const level = Math.floor(xp / EXPERIENCE_PER_LEVEL) + 1;
  return level > 100 ? 100 : level;
};

export const WEAPON_TYPES = {
  1: "AEG",
  2: "Spring",
  3: "GBB/GBBR",
  4: "HPA",
  5: "AEP (Pistola Elétrica)",
};

export const WEAPON_TYPES_OPTIONS = Object.entries(WEAPON_TYPES).map(
  ([index, label]) => ({
    label,
    value: Number.parseInt(index),
  }),
);

export const CATEGORIES = {
  1: "Assault",
  2: "DMR",
  3: "Sniper",
  4: "Support",
};

export const CATEGORIES_OPTIONS = Object.entries(CATEGORIES).map(
  ([index, label]) => ({
    label,
    value: Number.parseInt(index),
  }),
);

export const UNIFORM_IDS = {
  MULTICAM: 1,
  VERDE_MILITAR: 2,
  PMC: 3,
} as const;

export const UNIFORMS: Record<number, string> = {
  [UNIFORM_IDS.MULTICAM]: "Multicam",
  [UNIFORM_IDS.VERDE_MILITAR]: "Verde Militar",
  [UNIFORM_IDS.PMC]: "PMC",
};

export const UNIFORMS_OPTIONS = Object.entries(UNIFORMS).map(
  ([index, label]) => ({
    label,
    value: Number.parseInt(index),
  }),
);

export const PMC_EXCEPTIONS = ["helmet", "ski_mask"];

export const ROLES = [
  { label: "Administrador", value: "admin" },
  { label: "Armaria", value: "armorer" },
  { label: "Gestão Administrativa", value: "administrative" },
  { label: "Financeiro", value: "financial" },
  { label: "Eventos", value: "event" },
  { label: "Comunicação & Mídias", value: "media" },
  { label: "Operador", value: "operator" },
  { label: "Recruta", value: "recruit" },
  { label: "Padrão & Equipamentos", value: "uniform" },
  { label: "Visitante", value: "visitor" },
];

export const SHIRT_SIZES = ["PP", "P", "M", "G", "GG", "XG"];
export const BLOOD_TYPES = ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"];

export const EXPERIENCES = [
  { label: "Básico", value: 1 },
  { label: "Intermediário", value: 2 },
  { label: "Avançado", value: 3 },
];

export const SOURCES = [
  { label: "Membro (Indicação)", value: 1 },
  { label: "Redes Sociais", value: 2 },
  { label: "Grupo Online", value: 3 },
  { label: "Evento/Campo", value: 4 },
  { label: "Pesquisa Google", value: 5 },
  { label: "Site Oficial", value: 6 },
  { label: "Outro", value: 7 },
];

export const LOADOUT_ITEMS = [
  { key: "helmet", label: "Capacete", optional: false },
  { key: "bonnie_hat", label: "Bonnie Hat", optional: false },
  { key: "ski_mask", label: "Balaclava", optional: false },
  { key: "headset", label: "Headset", optional: false },
  { key: "combat_shirt", label: "Combat Shirt", optional: false },
  { key: "tactical_pants", label: "Calça Tática", optional: false },
  { key: "tactical_vest", label: "Colete Tático", optional: false },
  { key: "tactical_belt", label: "Cinto Tático", optional: false },
  { key: "gloves", label: "Luvas", optional: false },
  { key: "knee_pads", label: "Joelheira", optional: true },
  { key: "combat_boot", label: "Coturno", optional: false },
  { key: "holster", label: "Coldre", optional: false },
  { key: "walkie_talkie", label: "Rádio", optional: false },
];

export const ARSENAL_COLUMNS = [
  { field: "name", header: "Nome" },
  {
    field: "type",
    header: "Tipo",
    isTag: true,
    map: WEAPON_TYPES,
    severity: "contrast",
  },
  {
    field: "category",
    header: "Categoria",
    isTag: true,
    map: CATEGORIES,
    severity: "info",
  },
  { field: "joule", header: "Joule" },
  { field: "fps", header: "FPS" },
  { field: "maintained_at", header: "Última Manutenção", isDate: true },
];

export interface SkillAttribute {
  field: string;
  header: string;
  tag: string;
}

export type SkillStats = Record<string, number>;

export const SKILL_ATTRIBUTES: SkillAttribute[] = [
  { field: "honor", header: "Honra", tag: "HON" },
  { field: "aim", header: "Precisão", tag: "PRE" },
  { field: "tactics", header: "Tática", tag: "TAC" },
  { field: "communication", header: "Comunicação", tag: "COM" },
  { field: "mobility", header: "Mobilidade", tag: "MOB" },
  { field: "stealth", header: "Furtividade", tag: "FUR" },
  // { field: "awareness", header: "Percepção", tag: "PER" },
  // { field: "aggressiveness", header: "Ímpeto", tag: "IMP" },
  // { field: "stamina", header: "Resistência", tag: "RES" },
  // { field: "support", header: "Suporte", tag: "SUP" },
];

export const RADAR_OPTIONS: ChartOptions<"radar"> = {
  responsive: true,
  maintainAspectRatio: false,
  scales: {
    r: {
      angleLines: {
        display: true,
        color: "rgba(255, 255, 255, 0.15)",
      },
      grid: {
        color: "rgba(255, 255, 255, 0.15)",
      },
      suggestedMin: 0,
      suggestedMax: 5,
      ticks: {
        stepSize: 1,
        backdropColor: "transparent",
        color: "#9ca3af",
        font: { size: 10 },
      },
      pointLabels: {
        font: { size: 14, weight: "bold", family: "sans-serif" },
        color: "#e5e7eb",
      },
    },
  },
  plugins: {
    legend: { display: false },
    tooltip: {
      backgroundColor: "rgba(13, 21, 51, 0.95)",
      titleColor: "#DAA520",
      bodyFont: { size: 14 },
      padding: 12,
      borderColor: "rgba(218, 165, 32, 0.3)",
      borderWidth: 2,
      callbacks: {
        title: (context: TooltipItem<"radar">[]) => {
          const item = context[0];
          if (!item) return "";

          const index = item.dataIndex;

          return SKILL_ATTRIBUTES[index]?.header.toUpperCase() || "";
        },
      },
    },
  },
};

export const getRadarChartData = (stats: SkillStats): ChartData<"radar"> => {
  return {
    labels: SKILL_ATTRIBUTES.map((attr) => attr.tag),
    datasets: [
      {
        label: "Nível",
        data: SKILL_ATTRIBUTES.map((attr) => stats[attr.field] || 0),

        backgroundColor: "rgba(218, 165, 32, 0.3)",
        borderColor: "#DAA520",
        borderWidth: 2,
        pointBackgroundColor: "#DAA520",
        pointBorderColor: "#fff",
        pointHoverBackgroundColor: "#fff",
        pointHoverBorderColor: "#DAA520",
        fill: true,
      },
    ],
  };
};

export const EVENTS_COLUMNS = [
  { field: "title", header: "Titulo" },
  {
    field: "type",
    header: "Tipo",
    isTag: true,
    map: EVENT_TYPES,
    severity: "contrast",
  },
  { field: "date", header: "Data", isDate: true },
  { field: "location_name", header: "Localização" },
  { field: "description", header: "Descrição" },
];

export const RULES = ["RESCOM", "SAR", "MILSIM", "RUK"];

export const TEAMS = [
  "1º BAC",
  "Airsoft Paulo Afonso",
  "ANAT",
  "Arcanjo Porto Seguro",
  "Arcanjos da Chapada",
  "Arcanjos Soldiers",
  "Arkanjos",
  "Black Hawk",
  "Black Lions",
  "Black Ops",
  "Black Skull",
  "Black Weapon",
  "Blackout-SE",
  "Bratva",
  "Bravo",
  "Cães Selvagens Airsoft",
  "Canes",
  "CAPA",
  "Carcará",
  "CAS",
  "Casal Airsoft - Serrinha",
  "CAT",
  "CATA",
  "Catingueiros Airsoft Lençóis",
  "CEDAM",
  "CGAT",
  "Chakal",
  "Chivalry",
  "Cia de Airsoft Delta",
  "CITE",
  "Comando Selva",
  "COMANF",
  "Corvos de Amargosa",
  "COTA",
  "CPAT",
  "CTA - Petrolina",
  "Cyrus Company",
  "DCC -  Corisco do Cumbe",
  "Delta Force",
  "Desertores",
  "DETA",
  "Dias D'Ávila",
  "Dinops",
  "Dragons Tactical",
  "Drakkar",
  "E.F.A.S.",
  "Equipe Arcanjo",
  "Esquadrão Fantasma",
  TEAM_NAME,
  "F.E.A.T.",
  "FBI",
  "FEAR",
  "Fênix",
  "Fominhas",
  "Força Tática SSA",
  "Fortes Airsoft",
  "Frontline",
  "G.T.A.A.",
  "Gladiators",
  "GOAJ",
  "Havoc Team Airsoft",
  "IDFA",
  "Independente",
  "Kavock",
  "Kimera Airsoft",
  "Legionários",
  "Linat",
  "Lycans",
  "Mad Max",
  "Mamute",
  "Mercenários Alagoas",
  "Mercenários SSA",
  "Mossad",
  "Navy Seals",
  "Nika",
  "Panthers",
  "Pentágono",
  "Phantom",
  "Pintos de Briga Airsoft",
  "Psycho",
  "Outros",
  "Os Mercenários Team",
  "Outlaws",
  "Rangers",
  "Rangers - RAS",
  "Raptors",
  "RAT",
  "Red Dragon",
  "Renegados",
  "Ronin Tatical",
  "SAT",
  "SCAQ",
  "Seals Team",
  "Shaun Carneiro",
  "Sicário",
  "SKAT",
  "SKULL",
  "Sniper Team",
  "SOHAT",
  "Spartan Salvador",
  "Squad Caveira Esporte",
  "S.C.A.R.",
  "Tarja Preta",
  "Team Assault",
  "Team Six",
  "Terror",
  "Tier One",
  "TNT",
  "Tocaia",
  "TSA - Serrinha",
  "Urubus",
  "Terror - É o Bicho",
  "Ubatã Combat",
  "WR Airsoft 1ª Capital",
];

export const ALLERGIES = [
  "Abacate",
  "Abacaxi",
  "Abelha",
  "Açafrão",
  "Ácaros da poeira",
  "Ácaros da Poeira",
  "Ácido valpróico",
  "Acrilatos (Dentes/Unhas)",
  "Adesivos",
  "Aditivos alimentares",
  "Água (Aquagênica)",
  "Aipo",
  "Aipo (Salsão)",
  "Alcachofra",
  "Alcaparras",
  "Alecrim",
  "Algas (Nori)",
  "Algodão",
  "Alho",
  "Alpha-gal (Carne vermelha)",
  "Alternaria",
  "Amaciante de Roupa",
  "Amaciantes",
  "Ambrósia",
  "Ameixa",
  "Amêndoa",
  "Amendoim",
  "Amido de milho",
  "Amônia",
  "Amora",
  "Amoxicilina",
  "Ampicilina",
  "Anestésicos gerais",
  "Anestésicos Locais (Lidocaína)",
  "Anti-inflamatórios (Aspirina/Ibuprofeno)",
  "Anticonvulsivantes",
  "Aranha",
  "Arroz",
  "Aspargos",
  "Aspartame",
  "Aspergillus",
  "Aspirina (AAS)",
  "Atum",
  "Aveia",
  "Avelã",
  "Azitromicina",
  "Bacalhau",
  "Bacitracina",
  "Bálsamo do Peru",
  "Banana",
  "Barata (partículas em suspensão)",
  "Barata alemã",
  "Barata americana",
  "Baratas (Detritos)",
  "Baunilha",
  "Benzoato de sódio",
  "Benzocaína",
  "Berinjela",
  "Bicho-da-seda",
  "Borracha natural",
  "Cacau",
  "Caju (Fruta)",
  "Camarão",
  "Canela",
  "Carambola",
  "Caranguejo",
  "Carbamazepina",
  "Carmim (Inseto)",
  "Carne bovina",
  "Carne de cordeiro",
  "Carne de frango",
  "Carne de Porco",
  "Carne suína",
  "Carpa",
  "Carrapato",
  "Carvalho",
  "Caseína",
  "Castanha",
  "Castanha-de-caju",
  "Castanha-do-Pará",
  "Caviar / Ovas",
  "Cebola",
  "Cedro",
  "Cefalexina",
  "Ceftriaxona",
  "Celecoxibe",
  "Centeio",
  "Ceras",
  "Cereja",
  "Cetoprofeno",
  "Cevada",
  "Cevada maltada",
  "Chocolate",
  "Chocolate (Cacau ou Leite)",
  "Ciprofloxacino",
  "Cladosporium",
  "Claritromicina",
  "Clorexidina",
  "Cloro",
  "Cloro (Gás)",
  "Cobalto",
  "Cobalto (Metais)",
  "Cobre",
  "Codeína",
  "Coentro",
  "Cogumelo Shimeji",
  "Cogumelo Shitake",
  "Colas",
  "Conservantes (Parabenos)",
  "Contraste iodado",
  "Contraste radiológico",
  "Contrastes de Gadolínio",
  "Corante Tartrazina",
  "Corante Tartrazina (Amarelo 5)",
  "Corante Vermelho 40",
  "Cravo",
  "Cromo",
  "Cromo (Couro/Cimento)",
  "Damasco",
  "Dermatophagoides farinae",
  "Dermatophagoides pteronyssinus",
  "Detergentes",
  "Detergentes e Sabão em Pó",
  "Diclofenaco",
  "Dióxido de enxofre",
  "Dipirona",
  "Edamame",
  "Enoxaparina",
  "Epitélio de Cão",
  "Epitélio de Gato (Saliva/Pelo)",
  "Eritromicina",
  "Erva-doce",
  "Ervilha",
  "Escargot",
  "Escorpião",
  "Esmaltes",
  "Espelta",
  "Eucalipto",
  "Exercício físico (Anafilaxia induzida)",
  "Fava",
  "Feijão",
  "Fenitoína",
  "Fentanil",
  "Figo",
  "Formaldeído",
  "Formaldeído (Esmaltes)",
  "Formiga de fogo",
  "Formiga lava-pés",
  "Fragrâncias",
  "Fragrâncias e Perfumes",
  "Framboesa",
  "Fruta do conde",
  "Frutos do Mar (Lagosta/Siri)",
  "Frutos Secos (Damasco/Passas)",
  "Fungos",
  "Gafanhoto",
  "Gasolina",
  "Gelatina",
  "Geléia Real",
  "Gergelim",
  "Glutamato monossódico",
  "Glúten",
  "Grão-de-bico",
  "Grapefruit",
  "Grilo",
  "Heparina",
  "Hortelã",
  "Ibuprofeno",
  "IECA (Anti-hipertensivos)",
  "Insulina bovina",
  "Insulina suína",
  "Iodo",
  "Iodo / Contraste Radiológico",
  "Iodo povidona",
  "Isocianatos",
  "Isocianatos (Tintas)",
  "Kiwi",
  "Lã",
  "Lactose",
  "Lagosta",
  "Lagostim",
  "Lamotrigina",
  "Lanolina",
  "Laranja",
  "Látex",
  "Látex (Preservativos)",
  "Lecitina de soja",
  "Leite de vaca",
  "Lentilha",
  "Levofloxacino",
  "Lichia",
  "Lidocaína",
  "Limão",
  "Linguado",
  "Louro",
  "Lula",
  "Lupino",
  "Luz solar (Fotossensibilidade)",
  "Maçã",
  "Macadâmia",
  "Mamão",
  "Manga",
  "Manjericão",
  "Marimbondo",
  "Mel de abelha",
  "Melancia",
  "Melão",
  "Mexilhão",
  "Milho",
  "Mirtilo (Blueberry)",
  "Mofo",
  "Mofos e Fungos",
  "Moluscos",
  "Morango",
  "Morfina",
  "Mosquito",
  "Mostarda",
  "Naproxeno",
  "Neodímio (Ímãs)",
  "Neomicina",
  "Neoprene",
  "Nimesulida",
  "Níquel (bijuterias/botões)",
  "Níquel (Joias/Metais)",
  "Níquel em iPhones/Relógios",
  "Nitrato de prata",
  "Nitrofurantoína",
  "Noz",
  "Noz-moscada",
  "Noz-pecã",
  "Nozes e Castanhas",
  "Óleo de amendoim",
  "Óleo de gergelim",
  "Orégano",
  "Ostra",
  "Ouro",
  "Ovo (Clara)",
  "Ovo (Gema)",
  "Ovo (principalmente a clara)",
  "Ozônio",
  "Parabenos",
  "Paracetamol",
  "Parafenilenodiamina (PPD)",
  "Particulados de Diesel",
  "Pau-brasil (Pó)",
  "Peixe (Geral)",
  "Peixes (Bacalhau/Salmão)",
  "Pelo de cachorro",
  "Pelo de cavalo",
  "Pelo de coelho",
  "Pelo de Coelho",
  "Pelo de gato",
  "Pelo de hamster",
  "Pelo de porquinho-da-índia",
  "Penas de aves",
  "Penas de Aves",
  "Penicilina",
  "Penicilina (e derivados)",
  "Penicillium",
  "Pêra",
  "Percevejo",
  "Perfumes",
  "Pernilongo",
  "Pêssego",
  "Picada de Pernilongo",
  "Pimenta",
  "Pimentão",
  "Pinhão",
  "Pinheiro",
  "Pistache",
  "Pitaia (Dragão)",
  "Pó de camarão",
  "Pólen (Gramíneas e Flores)",
  "Pólen de árvores",
  "Pólen de ervas daninhas",
  "Pólen de flores",
  "Pólen de gramíneas",
  "Pólen-alimento (PFS)",
  "Polietilenoglicol (PEG)",
  "Polvo",
  "Prata",
  "Pressão na pele",
  "Prilocaína",
  "Produtos de limpeza",
  "Própolis",
  "Proteína do Leite de Vaca",
  "Protetor solar (PABA)",
  "Pulga",
  "Querosene",
  "Quimioterápicos",
  "Quinoa",
  "Quorn (Micoproteína)",
  "Rabanete",
  "Resina epóxi",
  "Romã",
  "Sabão em pó",
  "Sacarina",
  "Salmão",
  "Salsa",
  "Salsão",
  "Sálvia",
  "Sardinha",
  "Semente de abóbora",
  "Semente de girassol",
  "Semente de linhaça",
  "Semente de mostarda",
  "Semente de papoula",
  "Silicone de Próteses",
  "Siri",
  "Soja",
  "Solventes",
  "Soro antiofídico",
  "Soro de leite",
  "Sulfa",
  "Sulfa (Antibióticos)",
  "Sulfitos",
  "Sulfonamidas",
  "Suor (Urticária colinérgica)",
  "Taturana",
  "Terebentina",
  "Tetraciclina",
  "Tilápia",
  "Tintas de parede",
  "Tintura de cabelo",
  "Tintura de Cabelo (PPD)",
  "Tofu",
  "Tomate",
  "Tomilho",
  "Tramadol",
  "Tremoço",
  "Trigo",
  "Trigo (Glúten/Proteína)",
  "Triticale",
  "Trufas",
  "Truta",
  "Umidade",
  "Urticária ao calor",
  "Urticária ao frio",
  "Vacina da gripe (Ovo)",
  "Vacina Tríplice Viral",
  "Veneno de Abelha",
  "Veneno de Formiga",
  "Vespa",
  "Vibração",
  "Vieira",
  "Vitamina B12",
  "Zangão",
];

export const MEDICATIONS = [
  "Acarbose",
  "Acetazolamida",
  "Acetilcisteína",
  "Aciclovir",
  "Ácido Acetilsalicílico (AAS)",
  "Ácido Alendrônico",
  "Ácido Fólico",
  "Ácido Ursodesoxicólico",
  "Ácido Valproico",
  "Adrenalina (Epinefrina)",
  "Albendazol",
  "Alfenanil",
  "Alopurinol",
  "Alprazolam",
  "Ambroxol",
  "Amilorida",
  "Aminofilina",
  "Amiodarona",
  "Amitriptilina",
  "Amoxicilina",
  "Amoxicilina + Clavulanato",
  "Anastrozol",
  "Anlodipino",
  "Apixabana",
  "Atenolol",
  "Atorvastatina",
  "Atropina",
  "Azatioprina",
  "Azitromicina",
  "Baclofeno",
  "Benzoato de Benzila",
  "Betaistina",
  "Betametasona",
  "Bezafibrato",
  "Bicalutamida",
  "Bisacodila",
  "Bisoprolol",
  "Brimonidina",
  "Bromazepam",
  "Brometo de Ipratrópio",
  "Brometo de Tiotrópio",
  "Bromexina",
  "Bromoprida",
  "Budesonida",
  "Bupropiona",
  "Buspirona",
  "Capecitabina",
  "Captopril",
  "Carbamazepina",
  "Carbonato de Cálcio",
  "Carbonato de Lítio",
  "Carisoprodol",
  "Carvedilol",
  "Cefadroxila",
  "Cefalexina",
  "Ceftriaxona",
  "Celecoxibe",
  "Cetirizina",
  "Cetoconazol",
  "Cetoprofeno",
  "Ciclobenzaprina",
  "Ciclosporina",
  "Cinarizina",
  "Ciprofloxacino",
  "Ciproterona",
  "Citalopram",
  "Claritromicina",
  "Clindamicina",
  "Clobutinol",
  "Clomipramina",
  "Clonazepam",
  "Clopidogrel",
  "Cloreto de Potássio",
  "Clortalidona",
  "Codeína",
  "Colchicina",
  "Colestiramina",
  "Dabigatrana",
  "Dapagliflozina",
  "Desloratadina",
  "Desogestrel",
  "Desvenlafaxina",
  "Dexametasona",
  "Dextrometorfano",
  "Diazepam",
  "Diclofenaco Sódico",
  "Digoxina",
  "Dimenidrinato (Dramin)",
  "Diosmina + Hesperidina",
  "Dipirona Sódica",
  "Dobutamina",
  "Dolutegravir",
  "Domperidona",
  "Dopamina",
  "Doxiciclina",
  "Dropropizina",
  "Duloxetina",
  "Efavirenz",
  "Empagliflozina",
  "Enalapril",
  "Enoxaparina Sódica",
  "Entecavir",
  "Escitalopram",
  "Escopolamina (Buscopan)",
  "Esomeprazol",
  "Espironolactona",
  "Estradiol",
  "Estrogênios Conjugados",
  "Etinilestradiol + Gestodeno",
  "Etoricoxibe",
  "Ezetimiba",
  "Febuxostate",
  "Fenitoína",
  "Fenofibrato",
  "Fenoximetilpenicilina",
  "Fexofenadina (Allegra)",
  "Finasterida",
  "Fluconazol",
  "Fluoxetina",
  "Fluticasona",
  "Formoterol",
  "Furosemida",
  "Gabapentina",
  "Gentamicina",
  "Glibenclamida",
  "Gliclazida",
  "Glimepirida",
  "Glucagon",
  "Guaifenesina",
  "Haloperidol",
  "Hidralazina",
  "Hidroclorotiazida",
  "Hidrocortisona",
  "Hidroxicloroquina",
  "Hidróxido de Alumínio",
  "Hidróxido de Magnésio",
  "Hidroxizina",
  "Ibuprofeno",
  "Imatinibe",
  "Imipramina",
  "Insulina NPH",
  "Isosorbida",
  "Ivermectina",
  "Lactulose",
  "Lamivudina",
  "Lamotrigina",
  "Latanoprosta",
  "Letrozol",
  "Levetiracetam",
  "Levodropropizina",
  "Levofloxacino",
  "Levonorgestrel",
  "Levotiroxina Sódica",
  "Liraglutida (Saxenda)",
  "Loperamida",
  "Loratadina",
  "Lorazepam",
  "Losartana Potássica",
  "Maleato de Dexclorfeniramina",
  "Meclizina",
  "Medroxiprogesterona",
  "Meloxicam",
  "Mesalazina",
  "Metformina",
  "Metildopa",
  "Metoclopramida",
  "Metotrexato",
  "Metronidazol",
  "Midazolam",
  "Mirtazapina",
  "Montelucaste",
  "Morfina",
  "Mupirocina",
  "Nafazolina",
  "Naproxeno",
  "Neomicina + Bacitracina",
  "Nimesulida",
  "Nistatina",
  "Nitazoxanida (Annita)",
  "Nitrofurantoína",
  "Nitroglicerina",
  "Norfloxacino",
  "Nortriptilina",
  "Olanzapina",
  "Omeprazol",
  "Ondansetrona",
  "Orfenadrina",
  "Orlistate",
  "Oseltamivir (Tamiflu)",
  "Oximetazolina",
  "Pantoprazol",
  "Paracetamol",
  "Paroxetina",
  "Pentoxifilina",
  "Permetrina",
  "Pioglitazona",
  "Pirantel",
  "Piroxicam",
  "Prednisolona",
  "Prednisona",
  "Pregabalina",
  "Probenecida",
  "Progesterona",
  "Prometazina (Fenergan)",
  "Propofol",
  "Propranolol",
  "Quetiapina",
  "Rabeprazol",
  "Ranitidina",
  "Ribavirina",
  "Risperidona",
  "Ritonavir",
  "Rivaroxabana",
  "Rosuvastatina",
  "Saccharomyces boulardii",
  "Salbutamol",
  "Secnidazol",
  "Semaglutida (Ozempic)",
  "Sertralina",
  "Sibutramina",
  "Sildenafila (Viagra)",
  "Silimarina",
  "Simeticona (Luftal)",
  "Simvastatina",
  "Sitagliptina",
  "Sofosbuvir",
  "Sucralfato",
  "Sulfametoxazol + Trimetoprima",
  "Sulfassalazina",
  "Sulfato Ferroso",
  "Tadalafila",
  "Tamoxifeno",
  "Tansulosina",
  "Tenofovir",
  "Teofilina",
  "Terbinafina",
  "Teriparatida",
  "Timolol",
  "Tinidazol",
  "Tizanidina",
  "Topiramato",
  "Tramadol",
  "Trazodona",
  "Valsartana",
  "Varfarina Sódica",
  "Venlafaxina",
  "Vildagliptina",
  "Vitamina B12",
  "Vitamina D3 (Colecalciferol)",
  "Zolpidem",
];

export const TRANSACTION_CATEGORIES = [
  { value: "monthly_fee", label: "Mensalidade", severity: "success" },
  { value: "enrollment", label: "Matrícula/Adesão", severity: "success" },
  { value: "guest_fee", label: "Diária de Visitante", severity: "info" },
  { value: "event_registration", label: "Inscrição de Evento", severity: "info" },
  { value: "tournament_registration", label: "Inscrição do Torneio", severity: "info" },
  { value: "merchandise", label: "Vendas", severity: "success" },
  { value: "sponsorship", label: "Patrocínio / Parceria", severity: "success" },
  { value: "donation", label: "Doação Espontânea", severity: "success" },
  { value: "equipment_rental", label: "Aluguel de Equipamento", severity: "info" },
  { value: "training_service", label: "Treinamentos / Bootcamp", severity: "help" },
  { value: "prize_money", label: "Premiação de Torneio", severity: "success" },
  { value: "fine_penalty", label: "Multas / Penalidades", severity: "danger" },
  { value: "goal", label: "Metas", severity: "help" },
  { value: "field_maintenance", label: "Manutenção do Campo", severity: "warn" },
  { value: "armory", label: "Manutenção de AEGs/Backup", severity: "warn" },
  { value: "consumables", label: "Insumos (BBs/Gás)", severity: "warn" },
  { value: "fuel", label: "Combustível", severity: "danger" },
  { value: "marketing_media", label: "Mídia e Marketing", severity: "info" },
  { value: "banking_fees", label: "Taxas Bancárias", severity: "danger" },
  { value: "social_event", label: "Confraternização/Social", severity: "secondary" },
  { value: "guest_hospitality", label: "Recepção de Convidados", severity: "help" },
  { value: "hydration", label: "Hidratação", severity: "info" },
  { value: "operational_meal", label: "Almoço de Mutirão/Trabalho", severity: "warn" },
  { value: "safe_zone_food", label: "Coffee Break/Frutas", severity: "info" },
  { value: "travel_allowance", label: "Ajuda de Custo (Missão Externa)", severity: "secondary" },
  { value: "team_assets", label: "Patrimônio (Escudo/Cronos/Rádios)", severity: "warn" },
  { value: "safety_gear", label: "Segurança (EPI/Primeiros Socorros)", severity: "danger" },
  { value: "field_props", label: "Adereços de Missão (Bomas/Bandeiras)", severity: "warn" },
  { value: "visual_identity", label: "Identidade (Patches/Uniforme)", severity: "help" },
  { value: "awards_recognition", label: "Premiação e Mérito", severity: "help" },
  { value: "others", label: "Outros", severity: "secondary" },
];

export const TRANSACTION_STATUS = [
  { value: "created", label: "Emitido", severity: "secondary" },
  { value: "pending", label: "Pendente", severity: "warn" },
  { value: "overdue", label: "Vencido", severity: "danger" },
  { value: "paid", label: "Pago", severity: "success" },
];

export const CASHFLOW_TYPES = [
  { value: "income", label: "Entrada", severity: "success" },
  { value: "expense", label: "Saída", severity: "danger" },
];

export const COURSES = [
  { label: "Operador", value: TEAM_TAG, group: TEAM_TAG },
  { label: "Bootcamp FBDA 1", value: "bootcamp_fbda_1", group: "bootcamp" },
  { label: "Bootcamp FBDA 2", value: "bootcamp_fbda_2", group: "bootcamp" },
  { label: "Bootcamp FBDA 3", value: "bootcamp_fbda_3", group: "bootcamp" },
  { label: "Bootcamp FBDA 4", value: "bootcamp_fbda_4", group: "bootcamp" },
  { label: "Bootcamp FBDA 5", value: "bootcamp_fbda_5", group: "bootcamp" },
  { label: "SAR 1", value: "sar_1", group: "sar" },
  { label: "SAR 2", value: "sar_2", group: "sar" },
  { label: "FTA Cadete", value: "fta_cadet", group: "fta" },
  { label: "APH Combate", value: "aph_combat", group: "aph" },
];

export const AVAILABILITY_TYPES = [
  { label: "Sábado", value: "saturday" },
  { label: "Domingo", value: "sunday" },
  { label: "Fim de Semana", value: "both" },
];

export const PROFESSION_TYPES = [
  "Médico",
  "Advogado",
  "Engenheiro Civil",
  "Professor",
  "Arquiteto",
  "Contador",
  "Psicólogo",
  "Enfermeiro",
  "Dentista",
  "Veterinário",
  "Fisioterapeuta",
  "Nutricionista",
  "Farmacêutico",
  "Biólogo",
  "Geólogo",
  "Astrônomo",
  "Físico",
  "Químico",
  "Matemático",
  "Estatístico",
  "Arqueólogo",
  "Antropólogo",
  "Sociólogo",
  "Filósofo",
  "Historiador",
  "Geógrafo",
  "Jornalista",
  "Publicitário",
  "Designer Gráfico",
  "Ilustrador",
  "Fotógrafo",
  "Cinegrafista",
  "Editor de Vídeo",
  "Ator",
  "Dançarino",
  "Músico",
  "Maestro",
  "Escultor",
  "Pintor Artístico",
  "Escritor",
  "Tradutor",
  "Intérprete",
  "Bibliotecário",
  "Museólogo",
  "Arquivista",
  "Administrador",
  "Economista",
  "Corretor de Imóveis",
  "Corretor de Seguros",
  "Gerente de Vendas",
  "Vendedor",
  "Recepcionista",
  "Secretária",
  "Auxiliar Administrativo",
  "Porteiro",
  "Zelador",
  "Faxineiro",
  "Jardineiro",
  "Paisagista",
  "Agrônomo",
  "Zootecnista",
  "Pescador",
  "Agricultor",
  "Marceneiro",
  "Carpinteiro",
  "Pedreiro",
  "Mestre de Obras",
  "Eletricista",
  "Encanador",
  "Pintor Predial",
  "Gesseiro",
  "Serralheiro",
  "Soldador",
  "Mecânico",
  "Funileiro",
  "Estofador",
  "Alfaiate",
  "Costureira",
  "Modelo",
  "Cabeleireiro",
  "Barbeiro",
  "Manicure",
  "Esteticista",
  "Maquiador",
  "Tatuador",
  "Piercer",
  "Garçom",
  "Bartender",
  "Sommelier",
  "Barista",
  "Confeiteiro",
  "Açougueiro",
  "Peixeiro",
  "Cozinheiro",
  "Comissário de Bordo",
  "Guia de Turismo",
  "Agente de Viagens",
  "Piloto de Avião",
  "Motorista de Caminhão",
  "Motorista de Ônibus",
  "Maquinista",
  "Capitão de Navio",
  "Mergulhador",
  "Salva-vidas",
  "Bombeiro",
  "Policial",
  "Delegado",
  "Juiz",
  "Promotor",
  "Diplomata",
  "Político",
  "Guarda Municipal",
  "Vigilante",
  "Detetive",
  "Perito Criminal",
  "Paramédico",
  "Instrumentador Cirúrgico",
  "Radiologista",
  "Topógrafo",
  "Programador",
  "Analista de Sistemas",
  "Web Designer",
  "Social Media",
  "Gestor de Tráfego",
  "Copywriter",
  "Revisor",
  "Dublador",
  "Locutor",
  "Sonoplasta",
  "Iluminador",
  "Cenógrafo",
  "Figurinista",
  "Curador de Arte",
  "Joalheiro",
  "Relojoeiro",
  "Sapateiro",
  "Chaveiro",
  "Vidraceiro",
  "Marmorista",
  "Azulejista",
  "Engenheiro Químico",
  "Engenheiro Elétrico",
  "Engenheiro Mecânico",
  "Engenheiro de Produção",
  "Engenheiro Ambiental",
  "Engenheiro de Alimentos",
  "Engenheiro de Minas",
  "Engenheiro Naval",
  "Engenheiro Aeroespacial",
  "Engenheiro Biomédico",
  "Atleta",
  "Treinador",
  "Árbitro",
  "Preparador Físico",
  "Personal Trainer",
  "Instrutor de Yoga",
  "Piloto de Corrida",
  "Coreógrafo",
  "Malabarista",
  "Mágico",
  "Humorista",
  "Roteirista",
  "Produtor",
  "Diretor de Cinema",
  "Crítico",
  "Coach",
  "Consultor de RH",
  "Headhunter",
  "Auditor",
  "Despachante",
  "Agente Funerário",
  "Embalsamador",
  "Florista",
  "Adestrador",
  "Tosador",
  "Biotecnólogo",
  "Ecólogo",
  "Meteorologista",
  "Oceanógrafo",
  "Paleontólogo",
  "Cartógrafo",
  "Urbanista",
  "Decorador",
  "Organizador de Eventos",
  "Cerimonialista",
  "Relações Públicas",
  "Captador de Recursos",
  "Analista de Investimentos",
  "Trader",
  "Minerador",
  "Ourives",
  "Alfarrabista",
  "Calígrafo",
  "Cartunista",
  "Cenotécnico",
  "Cobrador",
  "Desenhista Industrial",
  "Ebanista",
  "Enólogo",
  "Paleógrafo",
];

export const MAINTENANCE_TYPES = [
  { label: "Revisão", value: "revison" },
  { label: "Reparo", value: "repair" },
  { label: "Upgrade", value: "upgrade" },
];

export const MAINTENANCE_STATUS_TYPES = [
  { label: "Aguardando Peças", value: "waiting" },
  { label: "Concluído", value: "completed" },
  { label: "Na Bancada", value: "bench" },
];

export const SCHEDULE_TYPES = {
  training: { label: "Treino de Arena", severity: "danger" },
  maintenance: { label: "Manutenção de Arena", severity: "warn" },
};

export const SCHEDULE_STATUS = {
  scheduled: { label: "Agendado", severity: "secondary" },
  completed: { label: "Concluído", severity: "success" },
  canceled: { label: "Cancelado", severity: "danger" },
};

export const VEHICLE_TYPES = {
  car: { label: "Carro", severity: undefined },
  motorcycle: { label: "Moto", severity: "secondary" },
  van: { label: "VAN", severity: "danger" },
  bus: { label: "Ônibus", severity: "warn" },
};